### ISSUE TITLE
Add unicode support? Unicode characters \u{...}

### ISSUE THREAD

**Issue by 18steps** [phadej/relaxed-json#16]
Can unicode support be added?

This example is just from a string in an array of strings

```
SyntaxError: Unexpected character: "; input: "\u{1F468} Simple\n\u{1F550} 30 minutes","...
    at C:\...\relaxed-json.js:70:21
    at Object.parse (C:\....\relaxed-json.js:528:33)
```

**Comment by ffischer1984** [comment]
have the same problem but with muted vowels e.g. ä,ü,ö
